### PR TITLE
Made changes to user and completed singleton class

### LINKED ISSUE #5: [Feature 1] user signup/login
feature includes:
- new user signup
- user login
- user logout

### PR DESCRIPTION
**Pull request by ileuxali**
Made 2 changes to User class:
1. made it an interface to allow multiple types of users, currently just normal user
2. deleted userID attribute, that attribute is giving us a lot of difficulty implementing, instead now we assume username attribute is unique

Also finished the implementation of the singleton class CurrentUser following Sohee's started code to store the current logged in user. Also included a test file to showcase how to use the singleton class.

### CODE REVIEW

**Review by SharonHsieh22 — CHANGES_REQUESTED** [review]
Change hashmaps to map Strings (username/groupName) to user/group objects. The rest looks good!

**Review by aaryavatsa — DISMISSED** [review]

**Review by SharonHsieh22 — DISMISSED** [review]
Thanks for making the changes. Approved!

**Review by ipekakyol — DISMISSED** [review]
All the new changes look good. Several use cases were dependent on the Singleton class as well as the IDs being changed to username/groupNames. Therefore, all the edits seem necessary and follow clean architecture principles.

**Comment by aaryavatsa** [comment]
Thanks for the quick update! Will take a look at resolving conflicts -- but the code looks good.

**Review by helenaglow — DISMISSED** [review]
This looks good! Thank you for adding getUserPublicProfile(). Also smart idea in making the User an interface. May want to consider a factory but your implementation looks good!

**Comment by ileuxali** [comment]
TA's suggestion: instead of storing an User entity in CurrentUser and pass it around use cases, store the username of the User entity in CurrentUser and pass that around, then in each use case the specific User is searched from database using the username.

**Review by ipekakyol — APPROVED** [review]
Applying the suggestions that our TA made seems to work well! Good job on the changes.

**Review by hannahpan1 — APPROVED** [review]
Looks good.

**Review by julia80887 — APPROVED** [review]
looks great!

**Pull request merged**
