### PR TITLE
example of actual clean architecture

### LINKED ISSUE #44: [Feature 1 update] User signup login screen link along with tests for feature

### PR DESCRIPTION
**Pull request by ileuxali**

### CODE REVIEW

**Review by aaryavatsa — DISMISSED** [review]
Looks good!

**Comment by ileuxali** [comment]
NEW IMPORTANT: use case updated to follow clean archetecture. Please refer and update your use cases accordingly.

**Review by aaryavatsa — APPROVED** [review]
i love clean archetecture and i love this pull request.

**Review by SharonHsieh22 — APPROVED** [review]
Archetecture is clean. Tests pass. No errors. Fixed everything

**Comment by soheegoo** [comment]
Good implementation of clean architecture as per the TA's comments on our Milestone 4.

**Review by soheegoo — APPROVED** [review]

**Pull request merged**
