### PR TITLE
Pending List and Group Members Screens

### LINKED ISSUE #8: [Feature 8] Edit pending list
Allows group leaders to accept and reject users from their groups' pending lists.

### LINKED ISSUE #50: [Feature 8 Update] Tests and screens
Completed all tests and screens

### PR DESCRIPTION
**Pull request by SharonHsieh22**
Dec 3, 2022:
- Screens are functional and connected to backend
- Registration, login, homepage, create group, new group profile, and pending list screens are connected
- Javadocs should be done
- Tests kinda incomplete

### CODE REVIEW

**Review by ileuxali — DISMISSED** [review]
Yes no screen in testing is good

**Review by aaryavatsa — DISMISSED** [review]
Looking great -- now i see how to use serialized data access 👍

**Review by aaryavatsa — APPROVED** [review]
WOOOOO

**Review by soheegoo — APPROVED** [review]

**Review by helenaglow — APPROVED** [review]
Looks good to me! Great screen implementation

**Review by ileuxali — APPROVED** [review]
amogus when the merge conflict is sus after first commit >:^(

**Pull request merged**
