### PR TITLE
Screens and refactoring

### PR DESCRIPTION
**Pull request by aaryavatsa**
DEC 4th:

don't look at this I'm showing Leo because my screens are messed up.

### CODE REVIEW

**Review by SharonHsieh22 — COMMENTED** [review]
Wait what's the naming convention for packages? I searched it up a while ago and it said all lower case (for sure) but then some places it says to put nothing between the words and some places it says to put a period between words...

**Comment by aaryavatsa** [comment]
> Wait what's the naming convention for packages? I searched it up a while ago and it said all lower case (for sure) but then some places it says to put nothing between the words and some places it says to put a period between words...

Hmm, that's interesting. I actually did not think to look up the conventions online at all 💯 I think it's more important (no matter what we decide) to just have cohesion in our project. I looked at Paul's naming and looked at Sohee's and Leo's and decided to match that. Use case packages are all lowercases with _ between words. files inside packages are AllCapitalized. renamed my Screens package to my_use_case_screens.

I can always refactor that though if we decide something else -- let's talk about this in our meeting tonight.

**Comment by SharonHsieh22** [comment]
> > Wait what's the naming convention for packages? I searched it up a while ago and it said all lower case (for sure) but then some places it says to put nothing between the words and some places it says to put a period between words...
> 
> Hmm, that's interesting. I actually did not think to look up the conventions online at all 💯 I think it's more important (no matter what we decide) to just have cohesion in our project. I looked at Paul's naming and looked at Sohee's and Leo's and decided to match that. Use case packages are all lowercases with _ between words. files inside packages are AllCapitalized. renamed my Screens package to my_use_case_screens.
> 
> I can always refactor that though if we decide something else -- let's talk about this in our meeting tonight.

Yeah we were following Paul's naming but the TA told us it was probably wrong last Monday LMAO.

**Comment by aaryavatsa** [comment]
> Yeah we were following Paul's naming but the TA told us it was probably wrong last Monday LMAO.

DID SHE REALLY?? let me just delete this pull request then 💯 💯

**Pull request closed without merging**
