### PR TITLE
1 feature 4 group creation

### PR DESCRIPTION
**Pull request by soheegoo**
Initial PR for Group Creation Use Case. 
- Includes data serialization for Groups (ReadWriters), database package with the .ser files where the data will be saved and test files with unit tests to ensure correctness of serialization
- Full functionality of Group Creation is added in accordance to Clean Architecture; the user who is logged in can create a group and it will be saved to the database
- GroupProfile isn't added to the Group entity as an attribute yet because I need Julia to push her GroupProfile entity first, or else I get an error since the class doesn't exist yet. 
- I also have my UI screens in the screens package, and also included my main file where I actually build the screen. Currently, the UI isn't functional because when I press RegisterGroup Button, I get an EOFException. However, the screen does display correctly
- Unit Tests and JavaDoc haven't been implemented yet

### CODE REVIEW

**Review by SharonHsieh22 — APPROVED** [review]
Serialization and repository-related classes/interfaces look good! Use case, entities and screens all follow clean architecture. We can check the naming convention for packages and change those later; for now, I think we can merge these commits into main.

**Review by aaryavatsa — APPROVED** [review]
Great work on the serialization and entities! Your tests look good too, and everything seems to follow the clean architecture principles. Really nice update after everything we discussed in tutorial and our group meeting today.

**Review by helenaglow — APPROVED** [review]
Congrats on finally getting serialization working! Like Sharon and Aarya said, your pull request seems to follow clean architecture really well. We can discuss further on how we will combine all our needs in the GeneralIDGateway. I see you changed group into an interface. Good idea!

**Comment by ileuxali** [comment]
Github having issues, check failed due to a DELETED TEST! WHY GITHUB THAT IS NOT SOMETHING TO TEST FOR!

**Pull request merged**
