### PR TITLE
Fixing screen connections and catching code smells 

### LINKED ISSUE #65: [Future Feature] Logout use case
Logout is implemented but not connected with screens due to complications with java swing. Will be looked into as a future addition.

### PR DESCRIPTION
**Pull request by helenaglow**
Fixed screen connection and some things 

TO-DO:
- [X] Fix connection between My Groups --x--> Edit Profile, instead My Groups ---> New Group Screen
- [X] Add logout option
- [X] Add View Group screen to the card layour

(_Special thanks to Sharon, Hannah, Julia & Leo for staying up so late with me grinding this out_)

### CODE REVIEW

**Review by soheegoo — DISMISSED** [review]

**Review by aaryavatsa — DISMISSED** [review]
wooo

**Review by aaryavatsa — DISMISSED** [review]
Amazing contribution. Thanks to everyone that worked on this -- especially you! screens look great and the consistency with the card layouts is well done. Great work on fixing the updating issues with the screens as well as code smells. Everything looks good

**Review by hannahpan1 — DISMISSED** [review]
Amazing work helena 🙌🙌. Thank you for all your hard work. Let’s fix the merge conflicts and then we’re good to go!

**Review by ileuxali — APPROVED** [review]
All of the linked screens are well done. The transitions were done beforehand but transfering data/updating data are well implemented in this pull request. Excellent work Helena.

**Review by hannahpan1 — APPROVED** [review]
Great job Helena!

**Review by soheegoo — APPROVED** [review]

**Review by julia80887 — APPROVED** [review]
INCREDIBLE CONTRIBUTION!! you are our saver Helena!

**Pull request merged**
