### PR TITLE
Non-hard-coded messages

### LINKED ISSUE #64: Non-hard-coded success and failure messages
Following our TA's feedback, we decided to avoid having hard-coded messages in our interactors by making a new class consisting of static messages that our interactors can call. We considered making get methods in this class and making it implement interfaces consisting of methods that each use case needs in order to invert depency and avoid duplicate code. However, we felt that this was overkill considering the basic nature of this class, so we chose to go with this method as recommended by Jonathon and another TA.

### PR DESCRIPTION
**Pull request by SharonHsieh22**
Added InteractorMessages class, polished everything.

### CODE REVIEW

**Review by ileuxali — APPROVED** [review]
I was doing this with her

**Comment by SharonHsieh22** [comment]
> I was doing this with her

you were playing genshin impact

**Comment by helenaglow** [comment]
Does everything work still? 


Refactoring is such an intimidating task cause what if you mess up. Thank you for doing this. Everything thing looks much more organized and adheres to the naming principles we assigned.

**Review by aaryavatsa — APPROVED** [review]
thank you SO MUCH. also thanks for going into the interactors and changing the error messages to the general class. you are a lifesaver !

also thank you for fixing the tests. the cascading effects of your touch.. like the refreshing coolness of a waterfall.

**Review by helenaglow — APPROVED** [review]

**Pull request merged**
