### PR TITLE
Cancel Application and Leave Group Screens

### LINKED ISSUE #42: [Feature 3] Cancel Application and Leave Group Screens

### PR DESCRIPTION
**Pull request by aaryavatsa**
My Applications Screen, My Groups Screen, View Group Profile Screens work and are connected. We can merge.

- don't mind the 80 files changed i'm so sorry i don't know how this happened. half of them are just because I refactored my package names.
- INFO: please just look at the commits for the new screens and use cases. everything else is just the product of weeks of work on my use case, as well as refactoring ,that was not merged regularly, oops!

TODO:

- [ ] refactor to throw exceptions in interactor, not screens

- [ ]  test View Application use case, View My Groups use case, View Group Profile use case

- [ ] increase code coverage -- include controller in testing use cases, and provide javadoc for how we would go about testing screens (according to Rui's testing coverage advice in email)

### CODE REVIEW

**Review by ileuxali — DISMISSED** [review]
I was here

**Review by soheegoo — DISMISSED** [review]

**Comment by soheegoo** [comment]
Great job connecting the screens. The screens with all the groups look great!

**Review by ileuxali — DISMISSED** [review]
I was with her doing these changes

**Review by soheegoo — APPROVED** [review]

**Review by ileuxali — APPROVED** [review]
yes

**Review by ipekakyol — APPROVED** [review]

**Pull request merged**
